---

- name: Copy flannel network conf file to master node
  template:
    src: flannel-conf.j2
    dest: /tmp/flannel-conf.json

- name: Initialized flannel network in etcd
  shell: etcdctl set /kubernetes-cluster/network/config < /tmp/flannel-conf.json

- name: Get flannel network details from etcd
  shell: etcdctl get /kubernetes-cluster/network/config
  register: etcd_flannel_net

- debug:
    var: etcd_flannel_net.stdout
