---

# Setup hosts and k8s package installation

#- hosts: kube-lb
#  become: true
#  become_method: sudo
#  vars_files:
#    - group_vars/all
#  roles:
#    - create-certs

#- hosts: master
#  become: true
#  become_method: sudo
#  vars_files:
#    - group_vars/all
#  roles:
#    - copy-files-to-master

#- hosts: nodes
#  become: true
#  become_method: sudo
#  vars_files:
#    - group_vars/all
#  roles:
#    - copy-files-to-worker

- hosts: master
  become: true
  become_method: sudo
  vars_files:
    - group_vars/all
  roles:
    - etcd-ha-non-https
