---
#- name: Install docker package
#  unarchive:
#    src: https://get.docker.com/builds/Linux/x86_64/docker-1.12.6.tgz
#    dest: /tmp
#    remote_src: True
#  ignore_errors: false

#- name: Copy docker binaries to /usr/bin
#  shell: mv /tmp/docker/docker* /usr/bin/
#  ignore_errors: false

- name: Clean remaining docker files from /tmp
  file:
    path: /tmp/docker
    state: absent

- name: Copy docker service template to all worker nodes
  template:
    src: docker-service.j2
    dest: /etc/systemd/system/docker.service
    mode: 0644
    backup: yes
  ignore_errors: false

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Start and enable docker service
  service:
    name: docker.service
    state: started
    enabled: yes
  ignore_errors: false

- name: check docker status
  shell: docker version
  register: docker_status
  ignore_errors: false

- debug:
    var: docker_status.stdout
