---

- name: Check if flanneld package already installed
  stat:
    path: /usr/bin/flanneld
  register: flanneld_file

- name: Install flannel package
  get_url:
    url: https://github.com/coreos/flannel/releases/download/v0.7.0/flanneld-amd64
    dest: /usr/bin/flanneld
    mode: 0755
  ignore_errors: false
  when: flanneld_file.stat.path is not defined

- name: Copy flanneld service template to all worker nodes
  template:
    src: flanneld-service.j2
    dest: /etc/systemd/system/flanneld.service
    mode: 0644
    backup: yes
  ignore_errors: false

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Start and enable flanneld service
  service:
    name: flanneld
    state: restarted
    enabled: yes
  ignore_errors: false

- name: check flanneld status
  shell: systemctl status flanneld --no-pager
  register: flanneld_status
  ignore_errors: false

- debug:
    var: flanneld_status.stdout

#- name: Install bridge-utils package
#  package:
#    name: bridge-utils
#    state: latest
