---

# The Kubernetes public IP address will be included in the list of subject alternative names for the Kubernetes server certificate.
# This will ensure the TLS certificate is valid for remote client access.

- name: Copy kubernetes-csr file
  template:
    src: kubernetes-csr.j2
    dest: /k8s-v1.7/certs/kubernetes-csr.json
    backup: no
  ignore_errors: false

- name: Generate the Kubernetes certificate and private key
  script: gen-kubernetes-srv-cert-key.sh
  ignore_errors: false
