---

# Download and Install kubectl in load balancer node (node which used to create certs or wants to use as client machine)

- name: Download and Install kubectl
  get_url:
    url: "{{k8s_ctl_pkg}}"
    dest: /usr/local/bin/
    mode: 0755
  sudo: true
