---

- name: Create a directory to store certificates in loadbalancer node
  file:
    path: /var/k8s-v1.7/certs
    state: directory
    owner: stack
    group: stack
    mode: 0755

- name: Copy CA config and csr files to lb node
  copy:
    src: "{{item}}"
    dest: /var/k8s-v1.7/certs/
  with_items:
    - ca-config.json
    - ca-csr.json
  ignore_errors: false

- name: Generate a CA certificate and private key "gen-ca-certs.sh"
  script: gen-ca-certs.sh
  ignore_errors: false
