---

- name: Create etcd directory
  file:
    path: /etc/etcd
    state: directory
    mode: 0755

- name: Copy the TLS certs to etcd directory
  command: cp ca.pem kubernetes-key.pem kubernetes.pem /etc/etcd
  ignore_errors: false

- name: Download etcd binary
  get_url:
    url: https://github.com/coreos/etcd/releases/download/v3.1.4/etcd-v3.1.4-linux-amd64.tar.gz
    dest: /tmp

- name: Extract etcd server binary and the etcdctl command line client
  command: cd /tmp/;tar -xvf etcd-v3.1.4-linux-amd64.tar.gz;mv etcd-v3.1.4-linux-amd64/etcd* /usr/bin/

- name: Create the etcd data directory
  file:
    path: /var/lib/etcd
    state: directory
    mode: 0755

- name: Delete downloaded etcd binary
  file:
    path: /tmp/etcd-v3.1.4-linux-amd64.tar.gz
    state: absent
