---

# The Kubelet can now use CNI - the Container Network Interface to manage machine level networking requirements.
# https://github.com/containernetworking/cni

- name: Create /opt/cni and /etc/cni/net.d directory
  file:
    path: "{{item}}"
    state: directory
    mode: 0755
  with_items:
    - /opt/cni
    - /etc/cni/net.d


- name: Install CNI package
  unarchive:
    src: https://storage.googleapis.com/kubernetes-release/network-plugins/cni-amd64-0799f5732f2a11b329d9e3d51b9c8f2e3759f2ff.tar.gz
    dest: /opt/cni
    remote_src: True
  ignore_errors: false

- name: Copy flannel network binary to /etc/cni/net.d
  command: cp /opt/cni/bin/flannel /etc/cni/net.d/

- name: Get pod_net_subnet value from flannel subnet.env
  shell: cat /run/flannel/subnet.env |grep -i subnet|cut -d'=' -f2
  register: pod_net_subnet

- debug:
    var: pod_net_subnet.stdout

- name: Copy cni-conf file to /etc/cni/net.d
  template:
    src: cni-conf.j2
    dest: /etc/cni/net.d/cni-conf.json
    mode: 0644
