---

- name: Install pacemaker and corosync
  package:
    name: {{item}}
    state: latest
  with_items:
     - pcs
     - pacemaker
     - corosync
     - fence-agents
     - resource-agents
  ignore_errors: false
  register: install_pcs_pkgs
  until: install_pcs_pkgs | success
  retries: 2
  delay: 5


- name: Start pcs service
  service:
    name: pcsd
    state: started
    enabled: yes
  ignore_errors: false
  register: pcs_svc
  until: pcs_svc | success
  retries: 3
  delay: 10
