---
# tasks file for pacemaker

- include: get-pc-corosync.yaml
- include: setup-cluster-auth.yaml
- include: setup-cluster.yaml
- include: get-pcs-status.yaml

#- name: Set Basic cluster properties
#  command: "{{item}}"
#  with_items:
#    - crm configure property pe-warn-series-max="1000" pe-input-series-max="1000" pe-error-series-max="1000" cluster-recheck-interval="5min"
#    - pcs property set pe-warn-series-max=1000 pe-input-series-max=1000 pe-error-series-max=1000 cluster-recheck-interval=5min
#  register: set_pcs_params
#  when: ansible_nodename=="{{controller1_host}}"
#  until: set_pcs_params | success
#  retries: 3
#  delay: 5
#  tags:
#    - set_param_pcs
