---

- name: Create kubernetes data directory in master nodes
  file:
    path: /var/lib/kubernetes
    state: directory
    mode: 0755

- name: Move certs and token to kubernetes data directory
  command: mv token.csv ca.pem ca-key.pem kubernetes-key.pem kubernetes.pem /var/lib/kubernetes/
  ignore_errors: false

- name: Download offcial kubernetes binaries
  get_url:
    url: "{{item}}"
    dest: /tmp
  with_items:
    - https://storage.googleapis.com/kubernetes-release/release/v1.7.0-alpha.3/bin/linux/amd64/kube-apiserver
    - https://storage.googleapis.com/kubernetes-release/release/v1.7.0-alpha.3/bin/linux/amd64/kube-controller-manager
    - https://storage.googleapis.com/kubernetes-release/release/v1.7.0-alpha.3/bin/linux/amd64/kube-scheduler
    - https://storage.googleapis.com/kubernetes-release/release/v1.7.0-alpha.3/bin/linux/amd64/kubectl

- name: Install kubernetes binaries
  command: "{{item}}"
  with_items:
    - chmod +x /tmp/{kube-apiserver,kube-controller-manager,kube-scheduler,kubectl}
    - mv /tmp/{kube-apiserver,kube-controller-manager,kube-scheduler,kubectl} /usr/bin/
