---

- name: Copy kube-apiserver service template to master nodes
  template:
    src: kube-apiserver.j2
    dest: /etc/systemd/system/kube-apiserver.service
    mode: 0644
    backup: no
  ignore_errors: false

- name: Reload systemd daemon
  command: systemctl daemon-reload
  ignore_errors: false

- name: Start and enable kube-apiserver service
  service:
    name: kube-apiserver.service
    state: started
    enabled: yes

- name: Check kube-apiserver service status
  shell: systemctl status kube-apiserver --no-pager
  register: api_srv_status
- debug:
    var: api_srv_status.stdout
