---

- name: Get failed kube-dns pods
  shell: kubectl get pods --namespace=kube-system |grep -i kube-dns |egrep  "CrashLoopBackOff|Error"
  register: failed_kubedns_pod
  ignore_errors: true

- fail:
    msg: "Found kube-dns pods in failed state!"
  register: dns_pod_fail_true
  when: failed_kubedns_pod | succeeded
  ignore_errors: true


- name: Delete failed kube-dns deployment
  shell: kubectl delete deployment kube-dns --namespace=kube-system
  register: del_dns_deployment
  when: dns_pod_fail_true | failed
  ignore_errors: false

- name: Remove remaining kube-dns component
  command: kubectl delete "{{item}}" kube-dns --namespace=kube-system
  with_items:
    - Service
    - ConfigMap
    - ServiceAccount
  when: dns_pod_fail_true | failed
  ignore_errors: false
